### ISSUE TITLE
Missing TOC

### ISSUE THREAD

**Issue by freddyb** [k88hudson/git-flight-rules#10]
A table of content would be nice, so you could read through possible sections if you're looking for a specific solution.
.
You could create a TOC manually, by observing the current README and linking to the headlines that github creates, e.g.
[What are flight rules](https://github.com/k88hudson/git-flight-rules#what-are-flight-rules)
[Conventions for this document](https://github.com/k88hudson/git-flight-rules#conventions-for-this-document)
...

Github also generates TOCs for wiki pages. So you could use the github repo wiki instead of the README file.

**Comment by RichardLitt** [comment]
Using Doctoc, seems to work.
