### ISSUE TITLE
Add "checkout to a remote branch that someone else is working on"

### ISSUE THREAD

**Issue by thomasyimgit** [k88hudson/git-flight-rules#107]
Thanks @k88hudson for creating such a awesome project. It could possibly save my day in the future.

I found that the `"checkout to a remote branch that someone else is working on"` is missing in the `Branch` section. And I could open a PR soon about this topic. 😄

**Comment by RichardLitt** [comment]
Thank you, @thomasyimgit! That worked great. :)
