### ISSUE TITLE
Shall it recommend --force-with-lease instead of just `git push -f`?

### ISSUE THREAD

**Issue by vi** [k88hudson/git-flight-rules#120]

**Comment by RichardLitt** [comment]
This looks like a duplicate of #8. If you have a specific PR to make to suggest this, go ahead and add it. 

On another note, this really oughtn't to be a place for suggestions, but instead a list of flight rules - things which work to get you out of a bind, and actions which will help do the job in a minimum of effort. Sometimes, `push -f` is called for over `--force-with-lease`. Something to keep in mind.

**Comment by annmarielarue** [comment]
content://media/external/file/620

**Comment by annmarielarue** [comment]
I don't understand
