### ISSUE TITLE
Add the use cases for git-branch --set-upstream-to

### ISSUE THREAD

**Issue by icyflame** [k88hudson/git-flight-rules#130]
I just needed to find out how to set the upstream to a local branch and I couldn't find it here. It should probably be added here.

**Comment by RichardLitt** [comment]
100%, @icyflame. Any chance you want to take a stab at it?

**Comment by icyflame** [comment]
Hey @RichardLitt, I will try to write a patch for this soon. :smile:

**Comment by RichardLitt** [comment]
@icyflame Any news on this? :)

**Comment by icyflame** [comment]
Hey @RichardLitt, I am extremely sorry about the delay! I have been completely swamped. I am free now, I will open a patch for this in the next 12 hours. Thanks for the reminder! :slightly_smiling_face:

**Comment by kanamouru123** [comment]
https://localbitcoins.com/buy-bitcoins-online/?ch=el7v

**Comment by RichardLitt** [comment]
No rush! Just wanted to check in. :)
