### ISSUE TITLE
I want to discard my local, uncommitted changes

### ISSUE THREAD

**Issue by xoco70** [k88hudson/git-flight-rules#150]
It seems in this section, you discard commited change, or am I misunderstanding ?

**Comment by RichardLitt** [comment]
Yes, I believe you are right there. https://github.com/k88hudson/git-flight-rules#i-want-to-discard-my-local-uncommitted-changes

It should follow these instructions, instead: https://stackoverflow.com/questions/14075581/git-undo-all-uncommitted-or-unsaved-changes

**Comment by hgautham** [comment]
Fixed in PR https://github.com/k88hudson/git-flight-rules/pull/160
