### ISSUE TITLE
Suggestion to improve "safety" when doing git operations

### ISSUE THREAD

**Issue by tadeu** [k88hudson/git-flight-rules#155]
First, I'd like to say that this is an awesome compilation of tasks/commands/problems, and it's very useful.

I'd like to suggest an improvement regarding the "safety" of git commands/operations. Newbies can be afraid of using more advanced things because of the "I'll lose my code" fear. There could be an introduction saying that git operations are generally safe, as long as _there are no dangling changes in the working directory_, i.e., everything is either _committed_ or _stashed_.

For example, the "I accidentally did a hard reset, and I want my changes back" session may give a false sense of safety, but it should be made clear that there's no `reflog` that will save uncommitted code after a `reset --hard` or a `checkout --force`.

What do you think?

**Comment by RichardLitt** [comment]
I think that makes sense. It should be framed as an introduction to various rules. "Note: for the next few rules, there is no excuse for not backing up work first. Bla bla bla..."

Want to PR? Sounds like you know what you want to do pretty well.
