### ISSUE TITLE
Snippet to customize git-log output

### ISSUE THREAD

**Issue by llrt** [k88hudson/git-flight-rules#192]
Could you please include some snippets related to customizing git-log output ?

**Comment by carusogabriel** [comment]
@llrt You mean colors, struct and so on?

**Comment by RichardLitt** [comment]
Let's assume that is what @llrt meant. Any PRs for this would be great.

**Comment by llrt** [comment]
I'm sorry for being absent for so long. I meant things like colors, pretty formatting, simple graph history of commits, files changed, authors, etc

Good refs on this topic is :
https://git-scm.com/docs/pretty-formats
https://medium.com/the-andela-way/exploring-the-git-log-command-9117b9ff3c2c

Both are good refs but exceedingly comprehensive; we should have simpler yet pleasant customized log snippets.

**Comment by RichardLitt** [comment]
I think the best person to do this is probably you. :) Feel free to PR something.
