### ISSUE TITLE
Remove big files from git history

### ISSUE THREAD

**Issue by deepakgangwar** [k88hudson/git-flight-rules#207]
Sometimes very big files are committed and can not be pushed any commit due to this previous commit so steps to remove such files and changing the git history should be included. 
Either the native git commands or [bfg](https://github.com/rtyley/bfg-repo-cleaner) will be a good option.

**Comment by RichardLitt** [comment]
I agree! A PR for this would be great. :)

**Comment by dustinfreeman** [comment]
I did a writeup of this exact problem here, when migrating away from git-lfs, using bfg:

https://dustinfreeman.org/blog/rip-lfs/

**Comment by dustinfreeman** [comment]
@deepakgangwar check out #249

**Comment by RichardLitt** [comment]
Close by #249. :)

**Comment by deepakgangwar** [comment]
Thank you @dustinfreeman and @RichardLitt
