### ISSUE TITLE
Default README file under different git-hosts

### ISSUE THREAD

**Issue by Cinderhaze** [k88hudson/git-flight-rules#211]
We have a mirror of git-flight-rules hosted on an internal gitlab server, and it picks the 'first' README* file, which selects `README-es.md` over `README.md`.  

Is it possible to have all the translations follow the standard of `README_ru.md` or `README_zh-CN.md`, which will leave the `README.md` as the default display in the repository?  

Also related - the `README-es.md` file isn't linked from the top of the `README.md` file

**Comment by RichardLitt** [comment]
I'm pretty sure this can be closed now. Glad you're getting mileage out of this list!
