### ISSUE TITLE
Section "Stash specific files" wrong?

### ISSUE THREAD

**Issue by ramiro** [k88hudson/git-flight-rules#216]
There is no `push` `git stash` sub-command so the two examples under this section

```
$ git stash push working-directory-path/filename.ext
```

```
$ git stash push working-directory-path/filename1.ext working-directory-path/filename2.ext
```

don't work.

**Comment by ramiro** [comment]
Sorry! I get an usage error message from my (older) git installation and didn't spot `push`is actually listed in the current docs at https://www.git-scm.com/docs/git-stash even when actually looking for it.

Sorry for the noise and wasting your time.

**Comment by RichardLitt** [comment]
No worries. :) We should add a note about what git version we're using for these commands.
