### ISSUE TITLE
Add fork subject

### ISSUE THREAD

**Issue by diegogsann** [k88hudson/git-flight-rules#268]
- I want to fork a repository (maybe explain why this is useful)
- I want to update my forked repository with original repository changes
- I want to send my changes to original repository

also, main topic could be 'contributing with others' or 'how to contribute to other git repositories'.

will be nice if someone bring other ideas to complement this suggestion. what you, guys, think about that?

**Comment by RichardLitt** [comment]
I think this is a great idea. I'd be happy to look at a PR for this. What you have here is a great start; no need to wait for more.

**Comment by dustinfreeman** [comment]
Definitely should include a clear description of why forking a repo is something you'd do!

**Comment by RichardLitt** [comment]
This is being solved in #274 and #275.

**Comment by RichardLitt** [comment]
Thanks for all the help, @diegogsann!
