### ISSUE TITLE
git stash apply

### ISSUE THREAD

**Issue by YaaMe** [k88hudson/git-flight-rules#284]
I think it can use 
`git stash apply` command (`stash history` is a stack)
instead of [switch stash](https://github.com/k88hudson/git-flight-rules#i-want-to-stage-my-unstaged-edits-and-unstage-my-staged-edits)

And I suggest to use [magit](https://github.com/magit/magit) or [Fugitive](https://github.com/tpope/vim-fugitive) or something else command tools bind on editor.So that you can avoid reciting too many git commands :)

**Comment by RichardLitt** [comment]
>  or something else command tools bind on editor.

Where do you mean? 

As far as `git stash apply` - PRs always welcome. :)

**Comment by YaaMe** [comment]
They maybe in part [tools](https://github.com/k88hudson/git-flight-rules#scripts-and-tools) I'm a emacs user so not sure what's the best choice in vim & vscode.
I notice `magit` use `git stash apply` to handle that case,I will check it at my free time.
