### ISSUE TITLE
Update previus commit (HEAD^) from another branch

### ISSUE THREAD

**Issue by konrado0905** [k88hudson/git-flight-rules#30]
# Example:

### master branch:
> commit d3f9e4ed239ec2836b13704a38db2c31e9615436
> Author: konrado0905
> Date:   Sun Aug 24 12:35:44 2014 +0200

>    First commit

### I'm creating new branch from master:
$ git co -b branch-1
$ touch second
$ git add second
$ git commit -m "Second commit"

### I'm creating new branch from branch-1:
$ git co -b branch-2
$ touch third
$ git add third
$ git commit -m "Third commit"
$ git log
> commit d2871010864f5746c245f140fdd46d36683abcd0
> Author: konrado0905
> Date:   Sun Aug 24 15:32:14 2014 +0200

>     Third commit

> commit 5913bad2636239ba2b102bc0e4dd2582e6dd50d1
> Author: konrado0905
> Date:   Sun Aug 24 12:36:34 2014 +0200

>     Second commit

> commit d3f9e4ed239ec2836b13704a38db2c31e9615436
> Author: konrado0905
> Date:   Sun Aug 24 12:35:44 2014 +0200

>     First commit

### I go back to branch-1:
$ git co branch-1
$ touch second-2
$ git add second-2
$ git commit --amend
$ git log
> commit 1c8db432f5af22ae193ef4b3b39805656be97baf
> Author: konrado0905
> Date:   Sun Aug 24 12:36:34 2014 +0200

>     Second commit (amended)

> commit d3f9e4ed239ec2836b13704a38db2c31e9615436
> Author: konrado0905
> Date:   Sun Aug 24 12:35:44 2014 +0200

>     First commit

**Comment by RichardLitt** [comment]
@konrado0905 I don't know if you're still interested in this problem, but the answer is simple: 

```sh
git co branch-2
git rebase branch-1
```

Done. 

Do you want us to add this to the document?

**Comment by konrado0905** [comment]
If you think this is useful then go ahead

**Comment by RichardLitt** [comment]
Cool. I'm not sure, it seems to be normal rebasing. I think we'll leave it out for now. Hope you understand it now!
