### ISSUE TITLE
Renaming from `master` to `main`

### ISSUE THREAD

**Issue by simaki** [k88hudson/git-flight-rules#308]
GitHub [plans to rename](https://github.com/github/renaming) the default branch from `master` to `main`.

The default branch name for new repositories is now `main`.
GitHub will provide tools to seamlessly switch the name of default branches of the existing repositories to `main`.

So I think it would be more convenient to replace `master` in our README with `main`.

**Comment by simaki** [comment]
I made a pull-request.

Thank you so much for a nice project!

**Comment by RichardLitt** [comment]
Thank you for noticing and for doing this work. I appreciate it.
