### ISSUE TITLE
Adding "How to split a branch in two" flight rule

### ISSUE THREAD

**Issue by ruijpbastos** [k88hudson/git-flight-rules#313]
I think it would be good to add a solution to split a branch into several branches, for the case where a lot of commits where added to a single branch but we now want to have them in different branches.

[Like this.](https://stackoverflow.com/a/28983843/7554194)

It's not exactly something that is recommended, but it can save people from some trouble (lets just say I know this from experience). I'm also free to open a PR for this.

**Comment by RichardLitt** [comment]
Sounds like a good rule to me. PRs accepted.

**Comment by ruijpbastos** [comment]
Created PR #314 .
