### ISSUE TITLE
General process for translations

### ISSUE THREAD

**Issue by VietThan** [k88hudson/git-flight-rules#316]
Hi,

I want to first thank @k88hudson and @RichardLitt for the wonderful work (and any other maintainers for this project). I can see that the translation projects are going strong and want to contribute to my mother tongue Vietnamese. I do have a general question about the process:
1. Is there any process to apply to be the maintainer for a specific language? What are the powers of a translation maintainer?
2. While making changes, I find that the Vietnamese version is out of date with regards to the English version, is there a way to ping/notify that the translations need to be updated? Or should there be a sentence like: "This version is updated to commit `SHA` on the English branch"?
3. Should the maintainers for different translations maintain different branches for their language?

Best,

Viet

**Comment by RichardLitt** [comment]
Hey @VietThan. Thanks for the thanks. 

There's no process. Right now, I think we're just using the standard PR process. There are no extra rights or powers given to a translator at the moment. If there are any issues in any translation, simply edit them locally and then submit a PR with the changes. All updates should be submitted to the main branch. Unfortunately, we don't have a way of showing that a translation is up to date or of pinging translators when a merge happens. Given the low-traffic of this repo at the moment, I'm not sure that is needed. 

Sorry if this is disappointing. I'd be happy to merge any updates, though. Any more questions?

**Comment by VietThan** [comment]
Thanks for the answers! These are all fine and I understand the situation. I do want to ask if maybe at least the Vietnamese branch can do our own keep check of tracking? like probably a chunk through comments at the beginning of the file?

**Comment by RichardLitt** [comment]
I wouldn't mind that. Go ahead. :) 

Closing this as not actionable. Feel free to reopen with more questions if you've got em.
