### ISSUE TITLE
reset without `--hard`

### ISSUE THREAD

**Issue by davidmatas** [k88hudson/git-flight-rules#33]
In `I committed to master instead of a new branch` section, is not better to do the reset without `--hard`?

`--hard` flag will destroy all the changes you made for the commit you want to recover in other branch so I think it is better to user without `--hard` to leave the changes unstaged.

**Comment by RichardLitt** [comment]
`git branch newbranch` saves those commits for you, so that they aren't lost. Just tested this, worked as expected and described.
