### ISSUE TITLE
"Unstaged Edits" includes repeated contents

### ISSUE THREAD

**Issue by lumynou5** [k88hudson/git-flight-rules#355]
`git reset` and `git checkout` are mentioned many times.
Furthermore, is these really about "unstaged edits"?

**Comment by lumynou5** [comment]
Suggestion:

- Staging
  - ...
  - I want to unstage changes
- Discarding changes
  - I want to discard uncommitted changes
  - I want to discard untracked changes

**Comment by RichardLitt** [comment]
Sounds like a good suggestion. PRs accepted!
