### ISSUE TITLE
Use git checkout --theirs or --ours . to resolve rebase conflicts

### ISSUE THREAD

**Issue by gesa** [k88hudson/git-flight-rules#4]
I'd write this bit myself but I don't actually fully understand how it works. I generally go with guess and check. And then I (re-) read [this blog post](http://gitready.com/advanced/2009/02/25/keep-either-file-in-merge-conflicts.html) over and over and over and over again.

**Comment by RichardLitt** [comment]
PRs would be great, if either or you (or anyone else) wants to take this on!
