### ISSUE TITLE
--force vs --force-with-lease

### ISSUE THREAD

**Issue by ncolton** [k88hudson/git-flight-rules#8]
I prefer to use --force-with-lease as a little bit of protection to make sure I don't stomp on changes made by someone else between the last update against the remote and when I do a forced push.

It is a bit safer, but I'm curious as to what others think.

**Comment by RichardLitt** [comment]
Does someone want to add a section about `--force-with-lease` to the README? That way, this information can be stored, and this ticket can be closed.

**Comment by RichardLitt** [comment]
Closed in #117!
