### ISSUE TITLE
Incorporate Git Cheatsheet?

### ISSUE THREAD

**Issue by RichardLitt** [k88hudson/git-flight-rules#90]
[This cheatsheet from GitHub](https://education.github.com/git-cheat-sheet-education.pdf)

**Comment by Trevoke** [comment]
I don't think that's worth it. People come to this repo when something has gone wrong and the cheat sheet can't help them.

**Comment by RichardLitt** [comment]
Fair point. 

Another resource: https://github.com/git-tips/tips

Still, could be written up as something to do when something goes wrong.

**Comment by RichardLitt** [comment]
Another resource: https://github.com/optionfactory/digit

**Comment by RichardLitt** [comment]
In the time since I opened this issue, the cheatsheet has moved. I've updated it.

I think that some of these things are useful. For instance, "Supressing tracking" would be a good thing to have on this list. In total, I think that adding these items from the cheatsheet would take roughly 30 minutes.

**Comment by k88hudson** [comment]
Having a section for common commands / common tasks is probably useful, even if the rest of the document is more focused on what to do when things go wrong.

**Comment by shubham171294** [comment]
I have the cheat sheet. Can I share it?

**Comment by eamanu** [comment]
The cheat sheet will be interest. I vote to put the cs in to some section.

**Comment by RichardLitt** [comment]
@shubham171294 I link it in the first issue. If you'd like to make some PRs and add it in, do so!

**Comment by shubham171294** [comment]
DONE. Please check.

**Comment by qWici** [comment]
@RichardLitt, @k88hudson 
I created two pdf files
1 - via [MarkdownToPDF](http://www.markdowntopdf.com/)
2 - via node module [markdown-pdf](https://www.npmjs.com/package/markdown-pdf)
We can make a vote. If the community says it's a good idea - you'll need to find or write your own auto-generator.

[README-via-markdowntopdf-com.pdf](https://github.com/k88hudson/git-flight-rules/files/1524059/README-via-markdowntopdf-com.pdf)
[README-via-node-markdown-pdf.pdf](https://github.com/k88hudson/git-flight-rules/files/1524057/README-via-node-markdown-pdf.pdf)

**Comment by RichardLitt** [comment]
Thanks @qWici  - I don't think that comment is part of this issue. Are you trying to follow up with #132?

**Comment by qWici** [comment]
@RichardLitt Yes, I did not see this issue. The question is closed.

**Comment by RichardLitt** [comment]
Hey all! I've jumped in and started filling out a branch showing how I would like this work to proceed, in #174. If you'd like to help out, jump in, grab a section, and add it!

**Comment by RichardLitt** [comment]
Closing as this is old. If anyone wants to jump in and add more commands from the cheatsheet, feel free!
