### ISSUE TITLE
"Flight rules for git - a work in progress!"

### ISSUE THREAD

**Issue by RichardLitt** [k88hudson/git-flight-rules#97]
Is this still a work in progress? Or can we just say "Flight Rules For Git?" :)

**Comment by RichardLitt** [comment]
@k88hudson Are you still interested in maintaining this project?

**Comment by RichardLitt** [comment]
@k88hudson Anual checkin. :)

**Comment by k88hudson** [comment]
I don't mind doing reviews, but I feel like it's in a pretty good state right now :)
